--ALTER SESSION SET container = XEPDB1;

CREATE USER dummyUser IDENTIFIED BY iamDummy;

CONNECT TO dummyUser;


GRANT CONNECT TO dummyUser;

GRANT CREATE SESSION TO dummyUser;

GRANT SELECT ON STUDENTS TO dummyUser;

GRANT SELECT ON BRANCH TO dummyUser;

SELECT * FROM STUDENTS;

SELECT * FROM ACCOUNTS;


