CREATE TABLE DRONE_FLEET (
    D_ID NUMBER(10) PRIMARY KEY,
    MODEL VARCHAR2(50) NOT NULL,
    ZONE VARCHAR2(100),
    STAT VARCHAR2(20) DEFAULT 'INACTIVE',
    B_LIFE NUMBER(3),
    MAINT_DATE DATE
);

INSERT INTO DRONE_FLEET VALUES (101, 'DJI Phantom 4', 'North Zone', 'ACTIVE', 85,'10-JAN-2024');
INSERT INTO DRONE_FLEET VALUES (102, 'Parrot Anafi', 'South Zone', 'INACTIVE', 40,'12-FEB-2018');
INSERT INTO DRONE_FLEET VALUES (103, 'Autel Evo II', 'West Zone', 'ACTIVE', 95,'18-JUN-2019');
INSERT INTO DRONE_FLEET VALUES (104, 'Skydio 2+', 'East Zone', 'ACTIVE', 70,'19-MAY-2019');

CREATE TABLE DELIVERY_ORDERS (
    O_ID NUMBER(10) PRIMARY KEY,
    D_ID NUMBER(10),
    CUST_NAME VARCHAR2(50) NOT NULL,
    DEST VARCHAR2(100),
    WEIGHT_KG NUMBER(5, 2),
    STATUS VARCHAR2(20),
    ORDER_DATE DATE,
    CONSTRAINT FK_DRONE FOREIGN KEY (D_ID) REFERENCES DRONE_FLEET (D_ID)
);

INSERT INTO DELIVERY_ORDERS VALUES (201, 101, 'Alice Johnson', 'Central Park', 2.50, 'DELIVERED','10-JAN-2024');
INSERT INTO DELIVERY_ORDERS VALUES (202, 102, 'Bob Smith', 'Brooklyn', 1.75, 'PENDING', '12-FEB-2018');
INSERT INTO DELIVERY_ORDERS VALUES (203, 104, 'Catherine Lee', 'Times Square', 3.25, 'IN TRANSIT', '18-JUN-2019');
INSERT INTO DELIVERY_ORDERS VALUES (204, 103, 'David Clark', 'Harlem', 4.00, 'DELIVERED','19-MAY-2019');


SELECT D_ID, CUST_NAME, DEST FROM DELIVERY_ORDERS ,DRONE_FLEET;

SELECT D_ID, CUST_NAME, DEST FROM DELIVERY_ORDERS CROSS JOIN DRONE_FLEET;

SELECT CUST_NAME, DEST FROM DELIVERY_ORDERS, DRONE_FLEET where DELIVERY_ORDERS.D_ID=DRONE_FLEET.D_ID;



SELECT d.CUST_NAME, d.DEST, df.D_ID, df.MODEL FROM DELIVERY_ORDERS d, DRONE_FLEET df WHERE d.D_ID=df.D_ID;

SELECT CUST_NAME,D_ID ,DEST FROM DELIVERY_ORDERS NATURAL JOIN DRONE_FLEET ;

SELECT CUST_NAME, DEST FROM DELIVERY_ORDERS JOIN DRONE_FLEET using(D_ID) where D_ID<=102;


SELECT CUST_NAME, DEST FROM DELIVERY_ORDERS d JOIN DRONE_FLEET df ON d.D_ID=df.D_ID;

SELECT * FROM DELIVERY_ORDERS D FULL OUTER JOIN DRONE_FLEET DF ON D.D_ID=DF.D_ID;

SELECT * FROM DELIVERY_ORDERS, DRONE_FLEET;



